### ISSUE TITLE
docker.sock support

### ISSUE THREAD

**Issue by skylord123** [naimo84/node-red-contrib-dockerode#1]
Can we get support for passing the docker.sock file in? I would prefer this over exposing my docker on the network.

**Comment by naimo84** [comment]
Hey skylord,
yes this should be possible. I'll try to implement this. 

Greetz, 
naimo

**Comment by naimo84** [comment]
Should work with version 0.3.2 ;)

Instead of a host, define the path to docker.sock:
![image](https://user-images.githubusercontent.com/11535502/65391346-69a0e480-dd68-11e9-8e3b-2f87fbbee419.png)

**Comment by skylord123** [comment]
Thanks man :)

**Comment by skylord123** [comment]
So I finally got around to testing this and it works perfectly. I only ran into one issue with the container not being able to access the mounted `docker.sock` file because it lacked permissions. I ended up finding this argument that needs to be added to the `docker run` call:

```
--group-add 281
```

You need to pass the ID of the docker group on your system. On my Unraid system this ended up being 281 but will probably be different for your system.

This may be good information to add to the docs.

**Comment by JustMaier** [comment]
Just stumbled through the process of doing this myself. I struggled to find my Docker Group ID, but finally figured it out by running:

```bash
getent group docker
```
