### ISSUE TITLE
Examples import shows unknown type

### ISSUE THREAD

**Issue by betonishard** [naimo84/node-red-contrib-dockerode#14]
Hi,

Thanks for your work.. It looks really nice.

I wanted to play around with it to see what are the possibilities, so the logical thing would be to check the examples, however the types are unknown although I have installed it via the "manage pallette" in node-red. THe message is "unknown-type" for all items such as docker-swarm or whatever type.

Thank you for your help!!

**Comment by naimo84** [comment]
Hi betonishard,

sorry for the delay. The current situation leads to less time for coding node-red 😞 
I'll try to fix this.

@ethanbrooks: Please do not change the node-names with every commit. This leads to something like this:
![image](https://user-images.githubusercontent.com/11535502/77614723-eb4b1800-6f2d-11ea-8cd1-66b820663205.png)

People will get error messages, if they update to a new version everytime.

Thanks and regards,
Benjamin
