### ISSUE TITLE
Keep original payload message and properties

### ISSUE THREAD

**Issue by skylord123** [naimo84/node-red-contrib-dockerode#2]
Currently these nodes override whatever the message had when it came into the node. This should actually keep the original message and just set the keys/values on that message object before returning it. 

A good example of why this is not the correct way is if you wire up HTTP request node before and a HTTP response node after one of the dockerode node's it wont be able to send the response because the `msg.response` is not defined (it was removed by the dockerode node).

**Comment by naimo84** [comment]
I will try to implement this. But I would like to keep overwriting the payload.
