### ISSUE TITLE
[FEAT]: Trigger the catch node when throwing an error

### ISSUE THREAD

**Issue by moritzlang** [naimo84/node-red-contrib-dockerode#28]
**Is your feature request related to a problem? Please describe.**
I want to handle errors that occur on the dockerode nodes.

**Describe the solution you'd like**
Any error should trigger the Catch node of nodered.

**Additional context**
Calling `node.error()` with one argument will not trigger a Catch node.
So instead of calling `node.error(err)` the function should be called with the original message as the second argument.
E.g.: `node.error(err, msg)`
[Documentation](https://nodered.org/docs/creating-nodes/node-js#handling-errors)

**Comment by naimo84** [comment]
hey @moritzlang,

[v0.12.0](https://flows.nodered.org/node/node-red-contrib-dockerode) is online. may you test it?

hopefully every error is catched now 😉


Greets
Benjamin

**Comment by moritzlang** [comment]
thanks for the quick adjustment @naimo84!
it works perfectly on my end now 👍
