### ISSUE TITLE
[FEAT]: No stream option for container stats

### ISSUE THREAD

**Issue by moritzlang** [naimo84/node-red-contrib-dockerode#29]
**Is your feature request related to a problem? Please describe.**
I would love to only pull the first stats of a container.

**Describe the solution you'd like**
Add a "no stream" option to the container stats node

**Additional context**
Docker supports a `--no-stream` option for container stats. [Documentation](https://docs.docker.com/engine/reference/commandline/stats/)

The implemantation would look something like this:
```js
  container.stats({ stream: false }, function (err, data) {
      if (err) {
          node.error('Error:', err)
      }

      node.send(data)
  });
```

**Comment by naimo84** [comment]
hey @moritzlang,

[v0.12.0](https://flows.nodered.org/node/node-red-contrib-dockerode) is online. may you test it?

a checkbox is added and the default is false. 

Greets
Benjamin

**Comment by moritzlang** [comment]
Thanks @naimo84!
Looks good for me 👍 

One thing I recognized when using the containers nodes:
Some commands (e.g. "stats") override the original msg object, some commands (e.g. "inspect") preserve the orignal msg obj. It would be nice to preserve the original message. This would be particularly useful when using the http nodes in Node-RED that require to preserve the response object in order to send the http response.
