### ISSUE TITLE
[BUG]: Unable to run container exec node with templated command

### ISSUE THREAD

**Issue by ashishbhatiya18** [naimo84/node-red-contrib-dockerode#31]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/986655/161430449-ad7b7907-2314-4314-ae9c-d70510ad9a46.png">
<img width="281" alt="image" src="https://user-images.githubusercontent.com/986655/161430461-ac808651-4113-48ad-b033-e5a3f7ff0b9f.png">

**Comment by naimo84** [comment]
Hi @ashishbhatiya18,

v0.12.1 is on the way. 

I'll close this for now ;)

Greets,
Benjamin
