### ISSUE TITLE
[FEAT]: delete container after run

### ISSUE THREAD

**Issue by eviltik** [naimo84/node-red-contrib-dockerode#34]
Thank you for this node-red contrib.

**Is your feature request related to a problem? Please describe.**
Delete a container after run it

**Describe the solution you'd like**
When action = run, add a checkbox "delete container after run"

**Describe alternatives you've considered**
docker events (where is the container id ? Actor.ID or Actor.Attributes.container ? + disconnect + container delete => no error but container not deleted

**Additional context**

**Comment by naimo84** [comment]
v0.13.0 is on the way 😉
