### ISSUE TITLE
[FEAT]: Not able to connect to docker setup with TLS

### ISSUE THREAD

**Issue by manuelh19** [naimo84/node-red-contrib-dockerode#49]
I've setup docker to run on TCP with TLS, because doing without wouldn't let me start docker. 
Now, neither in Node Red or in the Docs I see an option to configure dockerode with TLS. 

Am I overseeing something or is it not possible doing this? Or is there another way I have to configure docker to be useable without TLS?

**Comment by naimo84** [comment]
Might be fixed with the latest version.

If not feel free to comment or reopen it 😉
